branches:
  only:
    - master
language: python
python:
  - "2.7"
env:
  - TOXENV=py27
  - MAKE_TARGET=test
sudo: required
before_install:
  - sudo apt-get update
install: pip install coveralls tox
script: if [[ -n "$MAKE_TARGET" ]]; then make "$MAKE_TARGET"; else tox; fi
# after_success:
#   - coveralls
