branches:
  only:
  - master
language: python
python:
- '2.7'
env:
  global:
  - CAMPFIRE_TOKEN=abc123
  - TIMEOUT=1000
  - secure: ASPME62LiANnmdoSqGxSGeATlU4oCx4dSiSwrFjJQjMDqTkWh9mQAh5IlQnHV6ArXj5NRuTPCdOjZUZ+8OLR8ozz1+CnTTmjBc5Mx6ME0K2SKPynmYen7hRXpNFMP49+v3SfuQgLTNlmOAaZMMEozx/2PQqw/lmCuqQfOBjCYynnDe5ss2Clt/L0ObAT7pm1O3VK/cTHYw84LJF/5DpgdWVe2CCNtvygkAj06eQwBTH+WOM0ogT7/6VGx/dj5YhRm/czIPwTMF+RfWiRz24C40dJUvg2CTYbxIx3yKHD9B1kjY3aaxaYbsG+2Snf9xUBBwacoHfGnPAxMp7GLXN9Zmtrq6LpguaODtCvBrR3uSUOCIOmW94UrK99+AG8XOA47aH/dM1IHxHMvshC4c522EGYdZKjQWwCzFObBXnlgLPWlCBzgytLitAD6KlRICaDrXP0flU3PXC8+RuvYKR78wkHawRRhhboznmAdUPerdJwA8j6AExtEjNaT6RkRJ8wBAyVPPyt72FlFGFDSupp1NJvKa+GT+vj+AlDtYqYssIUGAXdpFAXp6D3yxiGU5x8GI0CCCH6ZIdBwuLQzmNLYmUVqoMtVipu/in0kxizmh1XWg4hQSIvnWISp+aS9vmbZXc3wNsI/Uwe1eGwUbDXn72Lu6n1QLjZVaQI5sEztM0=
  - secure: jK0P+qme4fKUXSXSkrOHdW1DtOuN/bOjKl9426qkpyY/EMaSgWFzpJa9PB4xgb8Ux9Td72TVJqiTvZC491rMzNrnKzM27CjDa8+lisC0hBc65SFCIQqAnqZIAEs85g8YLXbGthchfYvQEPkQ+A1779t4Nu7l7whiqqCcFziE8aihNrcaGh5/4j+dW6Pu40lzZMw4c0bT6xqYeX7JMHAyEXswW2gM2WXdo3ExRVhf+vjoTmZwM4+dcCi5g0QVm8WQbZGncByPKFkY9fizHSt85R11PN9Y84stC54Wxyur1jAYvl+UWvNMjQTYfLF4KWvsOQ2w3C04V+RZMSPsMmMufwrpEx2wRXaJ/K9enEYCu7RVR0DP5QVwXUIvn1bYZzIk4yoCz3va/V/kTtbKOF42iEp5qKHiwOgaFWHjvsXPQLbg2JaMjNzL0VVRAXnOwv+3ZsZD3sZyWXwvJrq4K1QNBt4X3MdmT/2DLtMVv/2IUWRIdp6UNJXSF4/3LkjXXx1tU8LLmM2hfQWFtLdC7R9ZRDgk3BKQ/v2i02yNNDIDhOPKjxBEckqAm5EoLo1vUMLBTMigxZs9Bbqe2fa5zEFg7YdN8OjNVZwjZ2dN5Y5zKWri5jI04yxzyLFXkEy52HGxBOZ0FNP/F2UGp9xGv1ijzXToZNz7oz5abvNW+LSFO94=
  - secure: RygRNJGSFW4vCx8hJzPNBT5kVkysZhEciflw19KyB3wN8s1s0j5LpsGKui327NV2l+sd5828IEL+cyCtrZdckjnnt538JP6b5QHcVFNX11pD7m2B6vNNZwixsOXFZDHGT3hvQeOX6B8QIPq3Eo+bHOJyYIUkELEMbHlLdarU8N0Fz/WZL2iFOTLhCWoTJ3B+hIGRzh8Me9lHRKLqsqAt+JNemo8dnD0xMoTNhEoOA8lKLlEG97dgO9KBTp3zW5KpHBIEkCCFrrs333o2//hhpUby6+2qsS3JrdORb8TzdXW0zPIZO9MhDuSYz6Sz25RVI9Q46N8xCVzO8soGPfMh7ZSXd4XLITvL3xXUh46jKhdMwTEevV4mqnDBxV5Gw0vVDf1biuTNuplxm5cpbvnUgZH8mwJHtjUIwkj8G0KuRhLy/D2wIVtTTT+QnDAwLjPvkFGmzKvmuKido5LYB09XnaG0Be/t4lARhhK8NcbPEr4DagK2mbO4lvlDzE7VS8aK2vZP5c4a8jRNtNJ2YNHfMyaqyQfyQLnqXjEThr5OUWpnIl+5wj/dbqZmTVqEUIdoSyTulCSsGR40i5LJtKk+dg17YoVUmpMVWWkBjOZlYPDSNc3YRU12Dm6sT1rLrEQmJSAv3hNNO9+Q/EdlCOFH3lwiO9gP8BtdnJmt80jBk5g=
  matrix:
  - MAKE_TARGET=test
sudo: required
before_install:
- sudo apt-get update
install: pip install coveralls tox
script: if [[ -n "$MAKE_TARGET" ]]; then make "$MAKE_TARGET"; else tox; fi
after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
    fi
